export const FETCH_REPORT = 'FETCH_REPORT';
export const FETCH_REPORT_INPROGRESS = 'FETCH_REPORT_INPROGRESS';
export const FETCH_UTILISATION = 'FETCH_UTILISATION';
export const FETCH_UTILISATION_INPROGRESS = 'FETCH_UTILISATION_INPROGRESS';